import { SiteHeader } from "../components/layout/SiteHeader";
import { SiteFooter } from "../components/layout/SiteFooter";

export default function Terms() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg)" }}>
      <SiteHeader />
      <section className="mx-auto max-w-2xl px-4 py-16 sm:px-6">
        <h1 className="text-3xl font-semibold" style={{ color: "var(--text-primary)" }}>
          Terms of Use
        </h1>
        <p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>
          Last updated September 2026. Placeholder terms for a demo application — not a real
          legal agreement.
        </p>

        <div className="prose-aether mt-8" style={{ color: "var(--text-secondary)" }}>
          <h2>Demo application</h2>
          <p>
            Aether is a practice project built to demonstrate frontend engineering and UI/UX design
            patterns for AI chat applications. It is not a commercial product, and Aether Labs is a
            fictional company used for demonstration purposes only.
          </p>

          <h2>AI-generated content</h2>
          <p>
            Responses in Aether are generated by Google's Gemini models. AI-generated content may be
            inaccurate, incomplete, or inappropriate for your use case. You are responsible for
            independently verifying any information before relying on it.
          </p>

          <h2>Third-party AI service</h2>
          <p>
            Aether relies on Google's Gemini API as a third-party service. Availability, performance,
            and behavior of generated responses are outside of Aether's control.
          </p>

          <h2>User responsibility</h2>
          <p>
            You are responsible for the content of messages you send and for keeping your own API
            key secure. Do not use Aether to submit sensitive personal, financial, or confidential
            information.
          </p>

          <h2>Availability</h2>
          <p>
            As a demo project, Aether is provided "as is" without guarantees of uptime, support, or
            continued availability.
          </p>

          <h2>Changes to these terms</h2>
          <p>
            These placeholder terms may be updated at any time without notice, as this project
            evolves.
          </p>
        </div>
      </section>
      <SiteFooter />
    </div>
  );
}
